export type NodeStatus = "online" | "busy" | "offline";
export type NodeKind = "iot" | "edge" | "cloud";
export type InfraNode = { id: string; kind: NodeKind; status: NodeStatus; cpu: number; memory: number; network: number; cpuTotal: number; memoryTotal: number; bandwidth: number; workloads: number; energy: number };
export type EventLevel = "INFO" | "SUCCESS" | "WARNING" | "ERROR";
export type SystemEvent = { id: number; time: string; level: EventLevel; message: string };

export const initialNodes: InfraNode[] = [
  ...Array.from({ length: 8 }, (_, i) => ({ id: `IoT-0${i + 1}`, kind: "iot" as const, status: (i === 7 ? "offline" : i === 2 ? "busy" : "online") as NodeStatus, cpu: 12 + i * 3, memory: 18 + i * 2, network: 15 + i * 4, cpuTotal: 1, memoryTotal: 512, bandwidth: 100, workloads: i === 2 ? 1 : 0, energy: 1.2 + i * .2 })),
  { id: "Edge-01", kind: "edge", status: "online", cpu: 41, memory: 58, network: 33, cpuTotal: 8, memoryTotal: 16, bandwidth: 1000, workloads: 2, energy: 9.8 },
  { id: "Edge-02", kind: "edge", status: "busy", cpu: 78, memory: 64, network: 52, cpuTotal: 12, memoryTotal: 32, bandwidth: 1500, workloads: 3, energy: 14.2 },
  { id: "Edge-03", kind: "edge", status: "online", cpu: 27, memory: 39, network: 24, cpuTotal: 8, memoryTotal: 16, bandwidth: 1000, workloads: 1, energy: 7.4 },
  { id: "Cloud-01", kind: "cloud", status: "online", cpu: 62, memory: 55, network: 46, cpuTotal: 64, memoryTotal: 256, bandwidth: 10000, workloads: 4, energy: 38.6 },
];

const cpu = [38,42,40,46,51,49,55,61,57,68,72,65,78,82,74,67,63,69,58,54,60,56,52,50];
export const initialMetrics = Array.from({ length: 24 }, (_, i) => ({ time: `${String(16 + Math.floor(i / 6)).padStart(2,"0")}:${String((i % 6) * 10).padStart(2,"0")}`, cpu: cpu[i], memory: 43 + Math.round(i * .7) + (i % 3), network: 320 + ((i * 137) % 1040), energy: +(1.1 + cpu[i] / 80).toFixed(1), execution: 55 + ((i * 17) % 72), latency: 8 + ((i * 11) % 48) }));

export const initialWorkloads = [
  ["W-101","IoT-01","Image Processing","2 CPU","1 GB","High","Edge-02","Running","00:00:12"],
  ["W-102","IoT-03","Analytics","4 CPU","2 GB","Medium","Cloud-01","Running","00:00:08"],
  ["W-103","IoT-06","Sensor Fusion","1 CPU","512 MB","Low","Edge-01","Queued","—"],
  ["W-104","IoT-04","Anomaly Scan","2 CPU","768 MB","High","Edge-03","Running","00:00:04"],
];

export const history = [
  ["W-098","IoT-02","Edge-01","82 ms","7 ms","4.3 J","SUCCESS"],
  ["W-099","IoT-05","Cloud-01","61 ms","41 ms","8.2 J","SUCCESS"],
  ["W-097","IoT-07","Edge-03","104 ms","12 ms","5.1 J","SUCCESS"],
  ["W-096","IoT-01","Edge-02","138 ms","18 ms","6.7 J","FAILED"],
];

export const initialEvents: SystemEvent[] = [
  { id: 1, time: "21:25:12", level: "SUCCESS", message: "Execution metrics received for W-098" },
  { id: 2, time: "21:25:12", level: "SUCCESS", message: "W-098 execution completed" },
  { id: 3, time: "21:25:07", level: "WARNING", message: "Edge-02 CPU utilization increased to 82%" },
  { id: 4, time: "21:25:05", level: "INFO", message: "W-101 execution started on Edge-02" },
  { id: 5, time: "21:25:04", level: "INFO", message: "Orchestrator assigned W-101 to Edge-02" },
  { id: 6, time: "21:25:03", level: "INFO", message: "Workload W-101 generated by IoT-01" },
];

export const dashboardDataAdapter = {
  endpoints: ["GET /api/devices", "GET /api/nodes", "GET /api/workloads", "GET /api/metrics", "GET /api/events", "WS /ws/metrics"],
  mode: "mock" as const,
};
